2020-09-02 22:19:43,892 CRITICAL config_server_log.py Критическая ошибка
2020-09-02 22:19:43,893 ERROR config_server_log.py Ошибка
2020-09-02 22:19:43,894 DEBUG config_server_log.py Отладочная информация
2020-09-02 22:19:43,894 INFO config_server_log.py Информационное сообщение
2020-09-02 22:20:31,064 INFO server.py Установлено соедение с ПК ('127.0.0.1', 51204)
2020-09-02 22:20:31,064 DEBUG server.py Получено сообщение {'action': 'presence', 'time': 1599060031.0645251, 'user': {'account_name': 'Client'}}
2020-09-02 22:20:31,065 DEBUG server.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1599060031.0645251, 'user': {'account_name': 'Client'}}
2020-09-02 22:20:31,066 INFO server.py Cформирован ответ клиенту {'response': 200}
2020-09-02 22:20:31,066 DEBUG server.py Соединение с клиентом ('127.0.0.1', 51204) закрывается.
2020-09-02 22:20:31,068 INFO server.py Установлено соедение с ПК ('127.0.0.1', 51205)
2020-09-02 22:20:31,069 DEBUG server.py Получено сообщение {'action': 'presence', 'time': 1599060031.0685253, 'user': {'account_name': 'Client'}}
2020-09-02 22:20:31,069 DEBUG server.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1599060031.0685253, 'user': {'account_name': 'Client'}}
2020-09-02 22:20:31,069 INFO server.py Cформирован ответ клиенту {'response': 200}
2020-09-02 22:20:31,069 DEBUG server.py Соединение с клиентом ('127.0.0.1', 51205) закрывается.
2020-09-02 22:20:31,082 INFO server.py Установлено соедение с ПК ('127.0.0.1', 51207)
2020-09-02 22:20:31,082 DEBUG server.py Получено сообщение {'action': 'presence', 'time': 1599060031.0815241, 'user': {'account_name': 'Client'}}
2020-09-02 22:20:31,082 DEBUG server.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1599060031.0815241, 'user': {'account_name': 'Client'}}
2020-09-02 22:20:31,082 INFO server.py Cформирован ответ клиенту {'response': 200}
2020-09-02 22:20:31,082 DEBUG server.py Соединение с клиентом ('127.0.0.1', 51207) закрывается.
2020-09-02 22:20:31,526 INFO server.py Установлено соедение с ПК ('127.0.0.1', 51203)
2020-09-02 22:20:31,526 DEBUG server.py Получено сообщение {'action': 'presence', 'time': 1599060031.5265565, 'user': {'account_name': 'Client'}}
2020-09-02 22:20:31,527 DEBUG server.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1599060031.5265565, 'user': {'account_name': 'Client'}}
2020-09-02 22:20:31,527 INFO server.py Cформирован ответ клиенту {'response': 200}
2020-09-02 22:20:31,527 DEBUG server.py Соединение с клиентом ('127.0.0.1', 51203) закрывается.
