2020-10-08 10:30:41,440 DEBUG decors.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2020-10-08 10:30:41,441 DEBUG decors.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2020-10-08 10:30:41,443 DEBUG decors.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2020-10-08 10:30:41,444 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2020-10-08 10:30:41,445 DEBUG server.py Аргументы успешно загружены.
2020-10-08 10:30:41,478 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2020-10-08 10:30:42,456 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62759)
2020-10-08 10:30:42,458 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62760)
2020-10-08 10:30:42,458 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62761)
2020-10-08 10:30:42,959 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602127842.4687188, 'user': {'account_name': 'Oleg', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzmCkZjMvTvTMorCc40Rx\nmHegO56XAPOREx34/aw04ptZPog7EL32K4FbeBYh4DrPAWeoFcB6ZiaijviFe6P9\nyrBT59G0AbJFfD+wPKra2ZLhkk1WOSolMNJT4bZwV7IcpyzVTj1V98N5AdIYZXDf\nFRtRSVQWkYJP63Soq2IaXIzaJLKPraIeINh6RGlLTEdjQmTTsK5+txwso3vn2xd3\n9rO86OjKcPZYtO9YizNuS7WnZUD0VFS6VP7yu0G3VU+iv7d0XvLZiE60Xp7adrwJ\nEl10TeQDZ6whQAkY0BmoXmfC+4BCQRPEZdwnnh33GZKw0qn/NSvScDvlzO3y2Sgv\nKQIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:30:42,959 DEBUG core.py Start auth process for {'account_name': 'Oleg', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzmCkZjMvTvTMorCc40Rx\nmHegO56XAPOREx34/aw04ptZPog7EL32K4FbeBYh4DrPAWeoFcB6ZiaijviFe6P9\nyrBT59G0AbJFfD+wPKra2ZLhkk1WOSolMNJT4bZwV7IcpyzVTj1V98N5AdIYZXDf\nFRtRSVQWkYJP63Soq2IaXIzaJLKPraIeINh6RGlLTEdjQmTTsK5+txwso3vn2xd3\n9rO86OjKcPZYtO9YizNuS7WnZUD0VFS6VP7yu0G3VU+iv7d0XvLZiE60Xp7adrwJ\nEl10TeQDZ6whQAkY0BmoXmfC+4BCQRPEZdwnnh33GZKw0qn/NSvScDvlzO3y2Sgv\nKQIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:30:42,968 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:30:42,972 DEBUG core.py Auth message = {'response': 511, 'bin': 'b8f8f40fe636e4e6195c4e09e9d78a86eb81ef48fbd15f371f8c1c7a9ef9f9260100c0d5ec262fa42e52fc9afb40d1babed31b283c469f4fd04cb46b92dfd0e3'}
2020-10-08 10:30:43,010 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602127842.4727259, 'user': {'account_name': 'Lena', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnQPZZ6dth0fPGaaaWoZd\nQ0PtS8kwuh/wEgXVlKwUnFS9SfZVuryA/Om8pH5n9e7pnhNRSNWXP/tXuf0/xD1t\nIBVv+wR3bBSNVEpDpBHye4r8y71MnXUmD2lCj2+B8GmDscZhyjQ0w2jC62hkDnMc\nrJ2d73RcJrrTs9OwxCW2YSJ3c79WJVLvNm6C8lUq2BKGperucH1AYlNP1nFJYMyf\n/nNnsFC0VAIw9CyciVSnFnvkHoS/BX8dQX6pwH8/pRe0dDkNtyHpte/Xz0dp/sEL\n6ixljiJHwvaGdIfU1DYC7n9o2XvWDmArXcIhhLJjtDOOuRIgh1k9hGnKqTeuMPFe\nBQIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:30:43,011 DEBUG core.py Start auth process for {'account_name': 'Lena', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnQPZZ6dth0fPGaaaWoZd\nQ0PtS8kwuh/wEgXVlKwUnFS9SfZVuryA/Om8pH5n9e7pnhNRSNWXP/tXuf0/xD1t\nIBVv+wR3bBSNVEpDpBHye4r8y71MnXUmD2lCj2+B8GmDscZhyjQ0w2jC62hkDnMc\nrJ2d73RcJrrTs9OwxCW2YSJ3c79WJVLvNm6C8lUq2BKGperucH1AYlNP1nFJYMyf\n/nNnsFC0VAIw9CyciVSnFnvkHoS/BX8dQX6pwH8/pRe0dDkNtyHpte/Xz0dp/sEL\n6ixljiJHwvaGdIfU1DYC7n9o2XvWDmArXcIhhLJjtDOOuRIgh1k9hGnKqTeuMPFe\nBQIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:30:43,023 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:30:43,025 DEBUG core.py Auth message = {'response': 511, 'bin': '613cfff434274aa1d5d13e26f1e781717edb568eb65c4cce90e1f9622cf4368d3d78766d88a3e1974bd46e70ac5d8c45ed893f8ef8bd7cb70a9414c93ac8fecf'}
2020-10-08 10:30:43,042 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602127842.47072, 'user': {'account_name': 'Dima', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4elxPrXi2TC515fun2//\nC9alciCYFrphla6kOA4iVr7DcB+1NXBPAMJulJt5O3XIgny8yrRRj+kdNJ7jrDe3\nW4RglWS0hzK0OcAdNI7rxu0cAA/WM+FP0RwcjCf5A3QTTU5Z75PLGi1YaQNFe+tc\nfTm2810qq07qP/xeSQv41aS95OFLQYiRo0Vuqa3sV7EVch05bG9ZI8abo30JotDf\nVau4qFJNgCDuwMZWHtTFeWCV+mngW84rWJHcJIm4aQpZRXIcHCxAdvByihv3HxN5\nUeNAca6DmDojd8ye8Se0wj+oRzgTx6HSXrTrq0Ex28+JwVnpSVbJ3c5beAQuTGbC\nWwIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:30:43,042 DEBUG core.py Start auth process for {'account_name': 'Dima', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4elxPrXi2TC515fun2//\nC9alciCYFrphla6kOA4iVr7DcB+1NXBPAMJulJt5O3XIgny8yrRRj+kdNJ7jrDe3\nW4RglWS0hzK0OcAdNI7rxu0cAA/WM+FP0RwcjCf5A3QTTU5Z75PLGi1YaQNFe+tc\nfTm2810qq07qP/xeSQv41aS95OFLQYiRo0Vuqa3sV7EVch05bG9ZI8abo30JotDf\nVau4qFJNgCDuwMZWHtTFeWCV+mngW84rWJHcJIm4aQpZRXIcHCxAdvByihv3HxN5\nUeNAca6DmDojd8ye8Se0wj+oRzgTx6HSXrTrq0Ex28+JwVnpSVbJ3c5beAQuTGbC\nWwIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:30:43,055 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:30:43,056 DEBUG core.py Auth message = {'response': 511, 'bin': 'a8d741a2e8beab8b0d31a34441eb9e30c7f406469b31c333b3c55ff0fa3c137a5653f120267ddc6e6a841341d6c3dad0383b93499b2f4481a6607f85d9c6878c'}
2020-10-08 10:30:43,577 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1602127842.9734046, 'account_name': 'Oleg'}
2020-10-08 10:30:43,578 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1602127843.0263987, 'account_name': 'Lena'}
2020-10-08 10:30:43,579 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1602127843.0578923, 'account_name': 'Dima'}
2020-10-08 10:30:44,081 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1602127843.599803, 'user': 'Oleg'}
2020-10-08 10:30:44,088 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1602127843.602803, 'user': 'Lena'}
2020-10-08 10:30:44,099 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1602127843.602803, 'user': 'Dima'}
2020-10-08 10:31:08,134 DEBUG core.py Разбор сообщения от клиента : {'action': 'add', 'time': 1602127867.9597235, 'user': 'Lena', 'account_name': 'Dima'}
2020-10-08 10:31:15,182 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1602127874.8501878, 'account_name': 'Dima'}
2020-10-08 10:31:23,710 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'Lena', 'to': 'Dima', 'time': 1602127883.4496758, 'message_text': 'JzyCCCL/v47d2pY1uECERr59FDIMwkYzGHh0Y5WCSbKJ4RVp3CgAn9nuFUfVBgM+eRA+SqOYp4Icq6G8W3QVFImL9j5d8DfEONhMZMceezv96uDGKO7F3Y6WkzSpGxCtQ/gYB0Pz8Sm6xEjSqS+oZcAweiU4kP5DQLHmOZehOOFzM4EslDQLPRgedIujhTqzGsGDfR497TSZMfdk30WI8yZJQldnoUNxJfXZW6OtHS+5uOPKRT9SxIxkXEKf+QadhYCAVOnnj/WwIoB5j9BGNx8nZHi62cZ39cj0AKR1TX6OxsrxktH7uoO4/CDmEgI/Wx6D1vgHLMAHCI9gaec/wg=='}
2020-10-08 10:31:23,743 INFO core.py Отправлено сообщение пользователю Dima от пользователя Lena.
2020-10-08 10:31:39,255 DEBUG core.py Разбор сообщения от клиента : {'action': 'add', 'time': 1602127899.2075267, 'user': 'Dima', 'account_name': 'Lena'}
2020-10-08 10:32:01,802 DEBUG core.py Getting data from client exception.
Traceback (most recent call last):
  File "C:\Users\User\Projects\MessengerProject\server\core.py", line 57, in run
    receive_message(client_with_message), client_with_message)
  File "C:\Users\User\Projects\MessengerProject\general\utils.py", line 7, in receive_message
    enc_answer = client.recv(MAX_PACKAGE_LEN)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2020-10-08 10:32:01,812 INFO core.py Клиент ('127.0.0.1', 62761) отключился от сервера.
2020-10-08 10:32:03,844 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1602127923.6305213, 'account_name': 'Oleg'}
2020-10-08 10:32:03,844 INFO core.py Клиент ('127.0.0.1', 62759) отключился от сервера.
2020-10-08 10:32:05,367 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1602127925.1573179, 'account_name': 'Lena'}
2020-10-08 10:32:05,367 INFO core.py Клиент ('127.0.0.1', 62760) отключился от сервера.
2020-10-08 10:32:13,915 DEBUG decors.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2020-10-08 10:32:13,915 DEBUG decors.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2020-10-08 10:32:13,917 DEBUG decors.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2020-10-08 10:32:13,918 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2020-10-08 10:32:13,918 DEBUG server.py Аргументы успешно загружены.
2020-10-08 10:32:13,963 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2020-10-08 10:32:14,956 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62764)
2020-10-08 10:32:14,968 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62765)
2020-10-08 10:32:14,973 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62766)
2020-10-08 10:32:14,973 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602127934.972002, 'user': {'account_name': 'Dima', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4elxPrXi2TC515fun2//\nC9alciCYFrphla6kOA4iVr7DcB+1NXBPAMJulJt5O3XIgny8yrRRj+kdNJ7jrDe3\nW4RglWS0hzK0OcAdNI7rxu0cAA/WM+FP0RwcjCf5A3QTTU5Z75PLGi1YaQNFe+tc\nfTm2810qq07qP/xeSQv41aS95OFLQYiRo0Vuqa3sV7EVch05bG9ZI8abo30JotDf\nVau4qFJNgCDuwMZWHtTFeWCV+mngW84rWJHcJIm4aQpZRXIcHCxAdvByihv3HxN5\nUeNAca6DmDojd8ye8Se0wj+oRzgTx6HSXrTrq0Ex28+JwVnpSVbJ3c5beAQuTGbC\nWwIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:32:14,973 DEBUG core.py Start auth process for {'account_name': 'Dima', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4elxPrXi2TC515fun2//\nC9alciCYFrphla6kOA4iVr7DcB+1NXBPAMJulJt5O3XIgny8yrRRj+kdNJ7jrDe3\nW4RglWS0hzK0OcAdNI7rxu0cAA/WM+FP0RwcjCf5A3QTTU5Z75PLGi1YaQNFe+tc\nfTm2810qq07qP/xeSQv41aS95OFLQYiRo0Vuqa3sV7EVch05bG9ZI8abo30JotDf\nVau4qFJNgCDuwMZWHtTFeWCV+mngW84rWJHcJIm4aQpZRXIcHCxAdvByihv3HxN5\nUeNAca6DmDojd8ye8Se0wj+oRzgTx6HSXrTrq0Ex28+JwVnpSVbJ3c5beAQuTGbC\nWwIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:32:14,985 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:32:14,986 DEBUG core.py Auth message = {'response': 511, 'bin': 'c1a9852d5413d957f730e0a7a51f363bec1d94c7a9b570211bcb56823e3837f4162c223135177eba4600c833da806c9039a612407b2da4a0e6b158c31fcad53e'}
2020-10-08 10:32:24,382 DEBUG decors.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2020-10-08 10:32:24,382 DEBUG decors.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2020-10-08 10:32:24,385 DEBUG decors.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2020-10-08 10:32:24,385 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2020-10-08 10:32:24,386 DEBUG server.py Аргументы успешно загружены.
2020-10-08 10:32:24,440 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2020-10-08 10:32:25,457 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62768)
2020-10-08 10:32:25,471 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62769)
2020-10-08 10:32:25,492 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62770)
2020-10-08 10:32:25,492 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602127945.4719534, 'user': {'account_name': 'Lena', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnQPZZ6dth0fPGaaaWoZd\nQ0PtS8kwuh/wEgXVlKwUnFS9SfZVuryA/Om8pH5n9e7pnhNRSNWXP/tXuf0/xD1t\nIBVv+wR3bBSNVEpDpBHye4r8y71MnXUmD2lCj2+B8GmDscZhyjQ0w2jC62hkDnMc\nrJ2d73RcJrrTs9OwxCW2YSJ3c79WJVLvNm6C8lUq2BKGperucH1AYlNP1nFJYMyf\n/nNnsFC0VAIw9CyciVSnFnvkHoS/BX8dQX6pwH8/pRe0dDkNtyHpte/Xz0dp/sEL\n6ixljiJHwvaGdIfU1DYC7n9o2XvWDmArXcIhhLJjtDOOuRIgh1k9hGnKqTeuMPFe\nBQIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:32:25,492 DEBUG core.py Start auth process for {'account_name': 'Lena', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnQPZZ6dth0fPGaaaWoZd\nQ0PtS8kwuh/wEgXVlKwUnFS9SfZVuryA/Om8pH5n9e7pnhNRSNWXP/tXuf0/xD1t\nIBVv+wR3bBSNVEpDpBHye4r8y71MnXUmD2lCj2+B8GmDscZhyjQ0w2jC62hkDnMc\nrJ2d73RcJrrTs9OwxCW2YSJ3c79WJVLvNm6C8lUq2BKGperucH1AYlNP1nFJYMyf\n/nNnsFC0VAIw9CyciVSnFnvkHoS/BX8dQX6pwH8/pRe0dDkNtyHpte/Xz0dp/sEL\n6ixljiJHwvaGdIfU1DYC7n9o2XvWDmArXcIhhLJjtDOOuRIgh1k9hGnKqTeuMPFe\nBQIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:32:25,496 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:32:25,497 DEBUG core.py Auth message = {'response': 511, 'bin': '3d1627d075ad1b76e6700d8011f0213331a1758411deee0bedb18e82f3e3c371790e101b8cce689eeaf61029f95bdd6bf9a4fbdd8240f06ae38343f60512cb7d'}
2020-10-08 10:32:25,520 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602127945.483954, 'user': {'account_name': 'Oleg', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzmCkZjMvTvTMorCc40Rx\nmHegO56XAPOREx34/aw04ptZPog7EL32K4FbeBYh4DrPAWeoFcB6ZiaijviFe6P9\nyrBT59G0AbJFfD+wPKra2ZLhkk1WOSolMNJT4bZwV7IcpyzVTj1V98N5AdIYZXDf\nFRtRSVQWkYJP63Soq2IaXIzaJLKPraIeINh6RGlLTEdjQmTTsK5+txwso3vn2xd3\n9rO86OjKcPZYtO9YizNuS7WnZUD0VFS6VP7yu0G3VU+iv7d0XvLZiE60Xp7adrwJ\nEl10TeQDZ6whQAkY0BmoXmfC+4BCQRPEZdwnnh33GZKw0qn/NSvScDvlzO3y2Sgv\nKQIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:32:25,520 DEBUG core.py Start auth process for {'account_name': 'Oleg', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzmCkZjMvTvTMorCc40Rx\nmHegO56XAPOREx34/aw04ptZPog7EL32K4FbeBYh4DrPAWeoFcB6ZiaijviFe6P9\nyrBT59G0AbJFfD+wPKra2ZLhkk1WOSolMNJT4bZwV7IcpyzVTj1V98N5AdIYZXDf\nFRtRSVQWkYJP63Soq2IaXIzaJLKPraIeINh6RGlLTEdjQmTTsK5+txwso3vn2xd3\n9rO86OjKcPZYtO9YizNuS7WnZUD0VFS6VP7yu0G3VU+iv7d0XvLZiE60Xp7adrwJ\nEl10TeQDZ6whQAkY0BmoXmfC+4BCQRPEZdwnnh33GZKw0qn/NSvScDvlzO3y2Sgv\nKQIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:32:25,530 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:32:25,531 DEBUG core.py Auth message = {'response': 511, 'bin': '43378bde32ff3930bd33b7a538a14a7acef6a804de325f2015395ba9467431a6bba8fcc9b20e9bac2f88ce8c3c3efc80afbef6ecc6509c9b06a654eb9e75bac1'}
2020-10-08 10:32:26,050 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1602127945.4989522, 'account_name': 'Lena'}
2020-10-08 10:32:26,070 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1602127945.5329595, 'account_name': 'Oleg'}
2020-10-08 10:32:26,072 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602127945.5019538, 'user': {'account_name': 'Dima', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4elxPrXi2TC515fun2//\nC9alciCYFrphla6kOA4iVr7DcB+1NXBPAMJulJt5O3XIgny8yrRRj+kdNJ7jrDe3\nW4RglWS0hzK0OcAdNI7rxu0cAA/WM+FP0RwcjCf5A3QTTU5Z75PLGi1YaQNFe+tc\nfTm2810qq07qP/xeSQv41aS95OFLQYiRo0Vuqa3sV7EVch05bG9ZI8abo30JotDf\nVau4qFJNgCDuwMZWHtTFeWCV+mngW84rWJHcJIm4aQpZRXIcHCxAdvByihv3HxN5\nUeNAca6DmDojd8ye8Se0wj+oRzgTx6HSXrTrq0Ex28+JwVnpSVbJ3c5beAQuTGbC\nWwIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:32:26,073 DEBUG core.py Start auth process for {'account_name': 'Dima', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4elxPrXi2TC515fun2//\nC9alciCYFrphla6kOA4iVr7DcB+1NXBPAMJulJt5O3XIgny8yrRRj+kdNJ7jrDe3\nW4RglWS0hzK0OcAdNI7rxu0cAA/WM+FP0RwcjCf5A3QTTU5Z75PLGi1YaQNFe+tc\nfTm2810qq07qP/xeSQv41aS95OFLQYiRo0Vuqa3sV7EVch05bG9ZI8abo30JotDf\nVau4qFJNgCDuwMZWHtTFeWCV+mngW84rWJHcJIm4aQpZRXIcHCxAdvByihv3HxN5\nUeNAca6DmDojd8ye8Se0wj+oRzgTx6HSXrTrq0Ex28+JwVnpSVbJ3c5beAQuTGbC\nWwIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:32:26,080 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:32:26,082 DEBUG core.py Auth message = {'response': 511, 'bin': '771f6845b7bd538a67a1ffe51fad8aee802ca4712d6262517771cf6d0f0388946494d1eb87012c65d4a8155e68283ea25edc5da91f23c1e23ca602c9c06046f7'}
2020-10-08 10:32:26,606 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1602127946.0940447, 'user': 'Lena'}
2020-10-08 10:32:26,614 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1602127946.0980434, 'user': 'Oleg'}
2020-10-08 10:32:26,620 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1602127946.0830438, 'account_name': 'Dima'}
2020-10-08 10:32:27,122 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1602127946.660368, 'user': 'Dima'}
2020-10-08 10:32:36,138 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1602127955.8868377, 'account_name': 'Lena'}
2020-10-08 10:32:38,142 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1602127957.7031105, 'account_name': 'Dima'}
2020-10-08 10:32:41,159 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1602127960.7508478, 'account_name': 'Lena'}
2020-10-08 10:32:46,168 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'Dima', 'to': 'Lena', 'time': 1602127965.9935784, 'message_text': 'QdT4Bh5cY5jkgJ2iyhxHkHmp4nq7EcHAL7wL0R2Xldf8G0N5DADa7JXLHsHJ7L/ht4v/+MgGA3fPHr1SpVLTlB/+JNN1tDzUdBN3xCPkdAWMkjE6KalVWM+o8uTjp0/D1QFaF6Sb2nb+gkMqqaPNPHce3gtiO8qDKs0rQu9+RyIsmLntQTKxDKKDvWl3Ki2Cf6q1OV7lONGwjsj+smkg+JXC06mwOrtuq5ABWQamb9eQoyhbQtGiD3QhCnWWMp+CiMHC4yex1f/Rf0kz6O0vAWKkMvwzGuOUZHbeucTCUM1cODzkKlRiQ2jyd6yg2/rNfGcwUK2+9tdVqjjr4Sy4hw=='}
2020-10-08 10:32:46,200 INFO core.py Отправлено сообщение пользователю Lena от пользователя Dima.
2020-10-08 10:33:09,246 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1602127989.0234485, 'account_name': 'Dima'}
2020-10-08 10:33:11,752 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1602127991.7501972, 'account_name': 'Dima'}
2020-10-08 10:33:22,264 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1602128001.9582818, 'account_name': 'Lena'}
2020-10-08 10:33:22,264 INFO core.py Клиент ('127.0.0.1', 62768) отключился от сервера.
2020-10-08 10:33:23,281 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1602128002.9840503, 'account_name': 'Dima'}
2020-10-08 10:33:23,281 INFO core.py Клиент ('127.0.0.1', 62770) отключился от сервера.
2020-10-08 10:33:24,298 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1602128004.2460682, 'account_name': 'Oleg'}
2020-10-08 10:33:24,298 INFO core.py Клиент ('127.0.0.1', 62769) отключился от сервера.
2020-10-08 10:33:33,726 DEBUG decors.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2020-10-08 10:33:33,726 DEBUG decors.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2020-10-08 10:33:33,728 DEBUG decors.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2020-10-08 10:33:33,728 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['C:/Users/User/Projects/MessengerProject/server.py']
2020-10-08 10:33:33,729 DEBUG server.py Аргументы успешно загружены.
2020-10-08 10:33:33,768 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2020-10-08 10:33:54,638 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62774)
2020-10-08 10:33:55,138 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602128034.6490648, 'user': {'account_name': 'Dima', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4elxPrXi2TC515fun2//\nC9alciCYFrphla6kOA4iVr7DcB+1NXBPAMJulJt5O3XIgny8yrRRj+kdNJ7jrDe3\nW4RglWS0hzK0OcAdNI7rxu0cAA/WM+FP0RwcjCf5A3QTTU5Z75PLGi1YaQNFe+tc\nfTm2810qq07qP/xeSQv41aS95OFLQYiRo0Vuqa3sV7EVch05bG9ZI8abo30JotDf\nVau4qFJNgCDuwMZWHtTFeWCV+mngW84rWJHcJIm4aQpZRXIcHCxAdvByihv3HxN5\nUeNAca6DmDojd8ye8Se0wj+oRzgTx6HSXrTrq0Ex28+JwVnpSVbJ3c5beAQuTGbC\nWwIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:33:55,138 DEBUG core.py Start auth process for {'account_name': 'Dima', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4elxPrXi2TC515fun2//\nC9alciCYFrphla6kOA4iVr7DcB+1NXBPAMJulJt5O3XIgny8yrRRj+kdNJ7jrDe3\nW4RglWS0hzK0OcAdNI7rxu0cAA/WM+FP0RwcjCf5A3QTTU5Z75PLGi1YaQNFe+tc\nfTm2810qq07qP/xeSQv41aS95OFLQYiRo0Vuqa3sV7EVch05bG9ZI8abo30JotDf\nVau4qFJNgCDuwMZWHtTFeWCV+mngW84rWJHcJIm4aQpZRXIcHCxAdvByihv3HxN5\nUeNAca6DmDojd8ye8Se0wj+oRzgTx6HSXrTrq0Ex28+JwVnpSVbJ3c5beAQuTGbC\nWwIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:33:55,149 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:33:55,153 DEBUG core.py Auth message = {'response': 511, 'bin': 'b0e8d2989981b4eb4f414b8a4bd0ca47b33211cab7355de54d74d607c79608330db81f187f04a57c5f944dd0fdbdeaa12144dd41e27d03ad5b73f1b5890a0790'}
2020-10-08 10:33:55,694 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1602128035.1543546, 'account_name': 'Dima'}
2020-10-08 10:33:56,216 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1602128035.7399564, 'user': 'Dima'}
2020-10-08 10:34:12,237 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1602128052.0960555, 'account_name': 'Lena'}
2020-10-08 10:34:24,251 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'Dima', 'to': 'Lena', 'time': 1602128064.0896783, 'message_text': 'TJXQFkyoaA+EniYFWyDLifG4nl5D/kw0tvt0XcH+IqFPbWksnMtRsG8VpTY3sT4kC3GSYnQlBZky3uOY8STU1Svj9QJLd9wH+ttHXODMcR5byzc1SHMH5tLmS7Zwvda2tK7WW88beRZWQ0JIjwkb1MfDUMtg5NSYa4r7ruh9zb+jodxlKCkk3ViH82P5JL3Ly3a6CgXMMNJIWuuUK/4SfLd9ewQ7bPRSNpWNTcfT4zqeM3LKx0YwUG8bU3drBQlls3EPbfJI3i0AxFPCFe5ncZqRurf+bCbg3L7z4IDj2AZHblh/j7a8P+CBdX1cJ0GHUnFIrUlLRHRlpnDqSNbPJA=='}
2020-10-08 10:34:54,783 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1602128094.4231684, 'account_name': 'Dima'}
2020-10-08 10:34:54,783 INFO core.py Клиент ('127.0.0.1', 62774) отключился от сервера.
2020-10-08 10:40:01,986 DEBUG decors.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2020-10-08 10:40:01,986 DEBUG decors.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2020-10-08 10:40:01,989 DEBUG decors.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2020-10-08 10:40:01,989 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2020-10-08 10:40:01,990 DEBUG server.py Аргументы успешно загружены.
2020-10-08 10:40:02,186 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2020-10-08 10:40:03,083 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62782)
2020-10-08 10:40:03,117 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62783)
2020-10-08 10:40:03,117 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602128403.0942698, 'user': {'account_name': 'Oleg', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzmCkZjMvTvTMorCc40Rx\nmHegO56XAPOREx34/aw04ptZPog7EL32K4FbeBYh4DrPAWeoFcB6ZiaijviFe6P9\nyrBT59G0AbJFfD+wPKra2ZLhkk1WOSolMNJT4bZwV7IcpyzVTj1V98N5AdIYZXDf\nFRtRSVQWkYJP63Soq2IaXIzaJLKPraIeINh6RGlLTEdjQmTTsK5+txwso3vn2xd3\n9rO86OjKcPZYtO9YizNuS7WnZUD0VFS6VP7yu0G3VU+iv7d0XvLZiE60Xp7adrwJ\nEl10TeQDZ6whQAkY0BmoXmfC+4BCQRPEZdwnnh33GZKw0qn/NSvScDvlzO3y2Sgv\nKQIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:40:03,117 DEBUG core.py Start auth process for {'account_name': 'Oleg', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzmCkZjMvTvTMorCc40Rx\nmHegO56XAPOREx34/aw04ptZPog7EL32K4FbeBYh4DrPAWeoFcB6ZiaijviFe6P9\nyrBT59G0AbJFfD+wPKra2ZLhkk1WOSolMNJT4bZwV7IcpyzVTj1V98N5AdIYZXDf\nFRtRSVQWkYJP63Soq2IaXIzaJLKPraIeINh6RGlLTEdjQmTTsK5+txwso3vn2xd3\n9rO86OjKcPZYtO9YizNuS7WnZUD0VFS6VP7yu0G3VU+iv7d0XvLZiE60Xp7adrwJ\nEl10TeQDZ6whQAkY0BmoXmfC+4BCQRPEZdwnnh33GZKw0qn/NSvScDvlzO3y2Sgv\nKQIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:40:03,129 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:40:03,131 DEBUG core.py Auth message = {'response': 511, 'bin': '5f9087244891426a070d990c965b5aa31c0e3c5177e919696ba906cf3122b9bddc58e5c803a5c50b8e80f59a82523633b37d15228fb94603153898e3f91e0a1b'}
2020-10-08 10:40:03,203 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62784)
2020-10-08 10:40:03,204 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1602128403.1322708, 'account_name': 'Oleg'}
2020-10-08 10:40:03,213 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602128403.128271, 'user': {'account_name': 'Dima', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4elxPrXi2TC515fun2//\nC9alciCYFrphla6kOA4iVr7DcB+1NXBPAMJulJt5O3XIgny8yrRRj+kdNJ7jrDe3\nW4RglWS0hzK0OcAdNI7rxu0cAA/WM+FP0RwcjCf5A3QTTU5Z75PLGi1YaQNFe+tc\nfTm2810qq07qP/xeSQv41aS95OFLQYiRo0Vuqa3sV7EVch05bG9ZI8abo30JotDf\nVau4qFJNgCDuwMZWHtTFeWCV+mngW84rWJHcJIm4aQpZRXIcHCxAdvByihv3HxN5\nUeNAca6DmDojd8ye8Se0wj+oRzgTx6HSXrTrq0Ex28+JwVnpSVbJ3c5beAQuTGbC\nWwIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:40:03,213 DEBUG core.py Start auth process for {'account_name': 'Dima', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4elxPrXi2TC515fun2//\nC9alciCYFrphla6kOA4iVr7DcB+1NXBPAMJulJt5O3XIgny8yrRRj+kdNJ7jrDe3\nW4RglWS0hzK0OcAdNI7rxu0cAA/WM+FP0RwcjCf5A3QTTU5Z75PLGi1YaQNFe+tc\nfTm2810qq07qP/xeSQv41aS95OFLQYiRo0Vuqa3sV7EVch05bG9ZI8abo30JotDf\nVau4qFJNgCDuwMZWHtTFeWCV+mngW84rWJHcJIm4aQpZRXIcHCxAdvByihv3HxN5\nUeNAca6DmDojd8ye8Se0wj+oRzgTx6HSXrTrq0Ex28+JwVnpSVbJ3c5beAQuTGbC\nWwIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:40:03,215 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:40:03,216 DEBUG core.py Auth message = {'response': 511, 'bin': '775b95b154e400dfd384e7c39ae81995225660776f1454332d91ebb46b283b0168a60c24d831f2df3d49df28a2c5bcc46cf27cd4cc1a3a6f553ca34b77cd2f91'}
2020-10-08 10:40:03,286 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602128403.1413233, 'user': {'account_name': 'Lena', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnQPZZ6dth0fPGaaaWoZd\nQ0PtS8kwuh/wEgXVlKwUnFS9SfZVuryA/Om8pH5n9e7pnhNRSNWXP/tXuf0/xD1t\nIBVv+wR3bBSNVEpDpBHye4r8y71MnXUmD2lCj2+B8GmDscZhyjQ0w2jC62hkDnMc\nrJ2d73RcJrrTs9OwxCW2YSJ3c79WJVLvNm6C8lUq2BKGperucH1AYlNP1nFJYMyf\n/nNnsFC0VAIw9CyciVSnFnvkHoS/BX8dQX6pwH8/pRe0dDkNtyHpte/Xz0dp/sEL\n6ixljiJHwvaGdIfU1DYC7n9o2XvWDmArXcIhhLJjtDOOuRIgh1k9hGnKqTeuMPFe\nBQIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:40:03,286 DEBUG core.py Start auth process for {'account_name': 'Lena', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnQPZZ6dth0fPGaaaWoZd\nQ0PtS8kwuh/wEgXVlKwUnFS9SfZVuryA/Om8pH5n9e7pnhNRSNWXP/tXuf0/xD1t\nIBVv+wR3bBSNVEpDpBHye4r8y71MnXUmD2lCj2+B8GmDscZhyjQ0w2jC62hkDnMc\nrJ2d73RcJrrTs9OwxCW2YSJ3c79WJVLvNm6C8lUq2BKGperucH1AYlNP1nFJYMyf\n/nNnsFC0VAIw9CyciVSnFnvkHoS/BX8dQX6pwH8/pRe0dDkNtyHpte/Xz0dp/sEL\n6ixljiJHwvaGdIfU1DYC7n9o2XvWDmArXcIhhLJjtDOOuRIgh1k9hGnKqTeuMPFe\nBQIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:40:03,301 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:40:03,303 DEBUG core.py Auth message = {'response': 511, 'bin': '390578366c00d1e3140ade05b800444d2ceac6364a86802cfd784e40634afcec44f431472fad7454e1fc9565e39672e02a01a1baf1cac8e99750d4d8e7889a9b'}
2020-10-08 10:40:11,891 DEBUG decors.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2020-10-08 10:40:11,891 DEBUG decors.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2020-10-08 10:40:11,894 DEBUG decors.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2020-10-08 10:40:11,894 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2020-10-08 10:40:11,895 DEBUG server.py Аргументы успешно загружены.
2020-10-08 10:40:12,164 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2020-10-08 10:40:13,078 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62787)
2020-10-08 10:40:13,104 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62788)
2020-10-08 10:40:13,128 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62789)
2020-10-08 10:40:13,128 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602128413.1084845, 'user': {'account_name': 'Lena', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnQPZZ6dth0fPGaaaWoZd\nQ0PtS8kwuh/wEgXVlKwUnFS9SfZVuryA/Om8pH5n9e7pnhNRSNWXP/tXuf0/xD1t\nIBVv+wR3bBSNVEpDpBHye4r8y71MnXUmD2lCj2+B8GmDscZhyjQ0w2jC62hkDnMc\nrJ2d73RcJrrTs9OwxCW2YSJ3c79WJVLvNm6C8lUq2BKGperucH1AYlNP1nFJYMyf\n/nNnsFC0VAIw9CyciVSnFnvkHoS/BX8dQX6pwH8/pRe0dDkNtyHpte/Xz0dp/sEL\n6ixljiJHwvaGdIfU1DYC7n9o2XvWDmArXcIhhLJjtDOOuRIgh1k9hGnKqTeuMPFe\nBQIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:40:13,128 DEBUG core.py Start auth process for {'account_name': 'Lena', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnQPZZ6dth0fPGaaaWoZd\nQ0PtS8kwuh/wEgXVlKwUnFS9SfZVuryA/Om8pH5n9e7pnhNRSNWXP/tXuf0/xD1t\nIBVv+wR3bBSNVEpDpBHye4r8y71MnXUmD2lCj2+B8GmDscZhyjQ0w2jC62hkDnMc\nrJ2d73RcJrrTs9OwxCW2YSJ3c79WJVLvNm6C8lUq2BKGperucH1AYlNP1nFJYMyf\n/nNnsFC0VAIw9CyciVSnFnvkHoS/BX8dQX6pwH8/pRe0dDkNtyHpte/Xz0dp/sEL\n6ixljiJHwvaGdIfU1DYC7n9o2XvWDmArXcIhhLJjtDOOuRIgh1k9hGnKqTeuMPFe\nBQIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:40:13,142 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:40:13,144 DEBUG core.py Auth message = {'response': 511, 'bin': 'f82e95b0a499096383979fe4a896306f5cee92ec5933c9136cc59b93913dda60ff025a4144d92541bf39048190cc1d9ccab4193599ad6bef818dba6f6fe74e31'}
2020-10-08 10:40:13,247 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602128413.1174834, 'user': {'account_name': 'Oleg', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzmCkZjMvTvTMorCc40Rx\nmHegO56XAPOREx34/aw04ptZPog7EL32K4FbeBYh4DrPAWeoFcB6ZiaijviFe6P9\nyrBT59G0AbJFfD+wPKra2ZLhkk1WOSolMNJT4bZwV7IcpyzVTj1V98N5AdIYZXDf\nFRtRSVQWkYJP63Soq2IaXIzaJLKPraIeINh6RGlLTEdjQmTTsK5+txwso3vn2xd3\n9rO86OjKcPZYtO9YizNuS7WnZUD0VFS6VP7yu0G3VU+iv7d0XvLZiE60Xp7adrwJ\nEl10TeQDZ6whQAkY0BmoXmfC+4BCQRPEZdwnnh33GZKw0qn/NSvScDvlzO3y2Sgv\nKQIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:40:13,247 DEBUG core.py Start auth process for {'account_name': 'Oleg', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzmCkZjMvTvTMorCc40Rx\nmHegO56XAPOREx34/aw04ptZPog7EL32K4FbeBYh4DrPAWeoFcB6ZiaijviFe6P9\nyrBT59G0AbJFfD+wPKra2ZLhkk1WOSolMNJT4bZwV7IcpyzVTj1V98N5AdIYZXDf\nFRtRSVQWkYJP63Soq2IaXIzaJLKPraIeINh6RGlLTEdjQmTTsK5+txwso3vn2xd3\n9rO86OjKcPZYtO9YizNuS7WnZUD0VFS6VP7yu0G3VU+iv7d0XvLZiE60Xp7adrwJ\nEl10TeQDZ6whQAkY0BmoXmfC+4BCQRPEZdwnnh33GZKw0qn/NSvScDvlzO3y2Sgv\nKQIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:40:13,263 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:40:13,265 DEBUG core.py Auth message = {'response': 511, 'bin': '4fd181105ba243cc8b69cd74f1496170a19593e1acb8b628a58e48840f7a1b19d1e8d62feb82a50b9033096f402909acc692d6438c99c46ad50ed35522c08e94'}
2020-10-08 10:40:27,567 DEBUG decors.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2020-10-08 10:40:27,567 DEBUG decors.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2020-10-08 10:40:27,570 DEBUG decors.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2020-10-08 10:40:27,570 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2020-10-08 10:40:27,571 DEBUG server.py Аргументы успешно загружены.
2020-10-08 10:40:27,612 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2020-10-08 10:40:28,575 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62791)
2020-10-08 10:40:28,577 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62792)
2020-10-08 10:40:28,585 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62793)
2020-10-08 10:40:29,086 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602128428.5904799, 'user': {'account_name': 'Lena', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnQPZZ6dth0fPGaaaWoZd\nQ0PtS8kwuh/wEgXVlKwUnFS9SfZVuryA/Om8pH5n9e7pnhNRSNWXP/tXuf0/xD1t\nIBVv+wR3bBSNVEpDpBHye4r8y71MnXUmD2lCj2+B8GmDscZhyjQ0w2jC62hkDnMc\nrJ2d73RcJrrTs9OwxCW2YSJ3c79WJVLvNm6C8lUq2BKGperucH1AYlNP1nFJYMyf\n/nNnsFC0VAIw9CyciVSnFnvkHoS/BX8dQX6pwH8/pRe0dDkNtyHpte/Xz0dp/sEL\n6ixljiJHwvaGdIfU1DYC7n9o2XvWDmArXcIhhLJjtDOOuRIgh1k9hGnKqTeuMPFe\nBQIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:40:29,086 DEBUG core.py Start auth process for {'account_name': 'Lena', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnQPZZ6dth0fPGaaaWoZd\nQ0PtS8kwuh/wEgXVlKwUnFS9SfZVuryA/Om8pH5n9e7pnhNRSNWXP/tXuf0/xD1t\nIBVv+wR3bBSNVEpDpBHye4r8y71MnXUmD2lCj2+B8GmDscZhyjQ0w2jC62hkDnMc\nrJ2d73RcJrrTs9OwxCW2YSJ3c79WJVLvNm6C8lUq2BKGperucH1AYlNP1nFJYMyf\n/nNnsFC0VAIw9CyciVSnFnvkHoS/BX8dQX6pwH8/pRe0dDkNtyHpte/Xz0dp/sEL\n6ixljiJHwvaGdIfU1DYC7n9o2XvWDmArXcIhhLJjtDOOuRIgh1k9hGnKqTeuMPFe\nBQIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:40:29,095 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:40:29,098 DEBUG core.py Auth message = {'response': 511, 'bin': 'd088e6b11dd9c47e68879d9528fbf7c44f5c74277568a30daceed80ca51dd8f8c8a97c65e882570db6c20dc72eaa97b6777984c0c21367e924b71c22b472c27b'}
2020-10-08 10:40:29,137 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602128428.5904799, 'user': {'account_name': 'Oleg', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzmCkZjMvTvTMorCc40Rx\nmHegO56XAPOREx34/aw04ptZPog7EL32K4FbeBYh4DrPAWeoFcB6ZiaijviFe6P9\nyrBT59G0AbJFfD+wPKra2ZLhkk1WOSolMNJT4bZwV7IcpyzVTj1V98N5AdIYZXDf\nFRtRSVQWkYJP63Soq2IaXIzaJLKPraIeINh6RGlLTEdjQmTTsK5+txwso3vn2xd3\n9rO86OjKcPZYtO9YizNuS7WnZUD0VFS6VP7yu0G3VU+iv7d0XvLZiE60Xp7adrwJ\nEl10TeQDZ6whQAkY0BmoXmfC+4BCQRPEZdwnnh33GZKw0qn/NSvScDvlzO3y2Sgv\nKQIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:40:29,137 DEBUG core.py Start auth process for {'account_name': 'Oleg', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzmCkZjMvTvTMorCc40Rx\nmHegO56XAPOREx34/aw04ptZPog7EL32K4FbeBYh4DrPAWeoFcB6ZiaijviFe6P9\nyrBT59G0AbJFfD+wPKra2ZLhkk1WOSolMNJT4bZwV7IcpyzVTj1V98N5AdIYZXDf\nFRtRSVQWkYJP63Soq2IaXIzaJLKPraIeINh6RGlLTEdjQmTTsK5+txwso3vn2xd3\n9rO86OjKcPZYtO9YizNuS7WnZUD0VFS6VP7yu0G3VU+iv7d0XvLZiE60Xp7adrwJ\nEl10TeQDZ6whQAkY0BmoXmfC+4BCQRPEZdwnnh33GZKw0qn/NSvScDvlzO3y2Sgv\nKQIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:40:29,147 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:40:29,148 DEBUG core.py Auth message = {'response': 511, 'bin': '5bc5db0a52e766ac53a90dd282c88f5f8299ee0ffda4f76ac2689ce3fd88527dc3bbedaf9ed047147bcc0e7e9e0b089b8fd2a0ee591cbbe601aae062e1d66df7'}
2020-10-08 10:40:29,168 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602128428.59848, 'user': {'account_name': 'Dima', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4elxPrXi2TC515fun2//\nC9alciCYFrphla6kOA4iVr7DcB+1NXBPAMJulJt5O3XIgny8yrRRj+kdNJ7jrDe3\nW4RglWS0hzK0OcAdNI7rxu0cAA/WM+FP0RwcjCf5A3QTTU5Z75PLGi1YaQNFe+tc\nfTm2810qq07qP/xeSQv41aS95OFLQYiRo0Vuqa3sV7EVch05bG9ZI8abo30JotDf\nVau4qFJNgCDuwMZWHtTFeWCV+mngW84rWJHcJIm4aQpZRXIcHCxAdvByihv3HxN5\nUeNAca6DmDojd8ye8Se0wj+oRzgTx6HSXrTrq0Ex28+JwVnpSVbJ3c5beAQuTGbC\nWwIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:40:29,168 DEBUG core.py Start auth process for {'account_name': 'Dima', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4elxPrXi2TC515fun2//\nC9alciCYFrphla6kOA4iVr7DcB+1NXBPAMJulJt5O3XIgny8yrRRj+kdNJ7jrDe3\nW4RglWS0hzK0OcAdNI7rxu0cAA/WM+FP0RwcjCf5A3QTTU5Z75PLGi1YaQNFe+tc\nfTm2810qq07qP/xeSQv41aS95OFLQYiRo0Vuqa3sV7EVch05bG9ZI8abo30JotDf\nVau4qFJNgCDuwMZWHtTFeWCV+mngW84rWJHcJIm4aQpZRXIcHCxAdvByihv3HxN5\nUeNAca6DmDojd8ye8Se0wj+oRzgTx6HSXrTrq0Ex28+JwVnpSVbJ3c5beAQuTGbC\nWwIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:40:29,184 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:40:29,186 DEBUG core.py Auth message = {'response': 511, 'bin': '791fcc1588b9433728b72aa532d75fffe147d9d10486de54b382e303717befbde3c784d7e8160ed013713fbc235be4c1af877cd228f0a275e2ce207ab21d9266'}
2020-10-08 10:40:29,704 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1602128429.1001124, 'account_name': 'Lena'}
2020-10-08 10:40:29,705 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1602128429.1491082, 'account_name': 'Oleg'}
2020-10-08 10:40:29,707 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1602128429.1871068, 'account_name': 'Dima'}
2020-10-08 10:40:30,208 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1602128429.732855, 'user': 'Lena'}
2020-10-08 10:40:30,216 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1602128429.7373614, 'user': 'Oleg'}
2020-10-08 10:40:30,222 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1602128429.7383742, 'user': 'Dima'}
2020-10-08 10:40:32,230 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1602128432.1286664, 'account_name': 'Dima'}
2020-10-08 10:40:32,230 INFO core.py Клиент ('127.0.0.1', 62793) отключился от сервера.
2020-10-08 10:43:32,918 DEBUG decors.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2020-10-08 10:43:32,918 DEBUG decors.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2020-10-08 10:43:32,918 DEBUG decors.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2020-10-08 10:43:32,918 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2020-10-08 10:43:32,934 DEBUG server.py Аргументы успешно загружены.
2020-10-08 10:43:32,965 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2020-10-08 10:43:38,856 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62828)
2020-10-08 10:43:38,858 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62829)
2020-10-08 10:43:38,868 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62830)
2020-10-08 10:43:39,369 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602128618.8709276, 'user': {'account_name': 'Oleg', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzmCkZjMvTvTMorCc40Rx\nmHegO56XAPOREx34/aw04ptZPog7EL32K4FbeBYh4DrPAWeoFcB6ZiaijviFe6P9\nyrBT59G0AbJFfD+wPKra2ZLhkk1WOSolMNJT4bZwV7IcpyzVTj1V98N5AdIYZXDf\nFRtRSVQWkYJP63Soq2IaXIzaJLKPraIeINh6RGlLTEdjQmTTsK5+txwso3vn2xd3\n9rO86OjKcPZYtO9YizNuS7WnZUD0VFS6VP7yu0G3VU+iv7d0XvLZiE60Xp7adrwJ\nEl10TeQDZ6whQAkY0BmoXmfC+4BCQRPEZdwnnh33GZKw0qn/NSvScDvlzO3y2Sgv\nKQIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:43:39,369 DEBUG core.py Start auth process for {'account_name': 'Oleg', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzmCkZjMvTvTMorCc40Rx\nmHegO56XAPOREx34/aw04ptZPog7EL32K4FbeBYh4DrPAWeoFcB6ZiaijviFe6P9\nyrBT59G0AbJFfD+wPKra2ZLhkk1WOSolMNJT4bZwV7IcpyzVTj1V98N5AdIYZXDf\nFRtRSVQWkYJP63Soq2IaXIzaJLKPraIeINh6RGlLTEdjQmTTsK5+txwso3vn2xd3\n9rO86OjKcPZYtO9YizNuS7WnZUD0VFS6VP7yu0G3VU+iv7d0XvLZiE60Xp7adrwJ\nEl10TeQDZ6whQAkY0BmoXmfC+4BCQRPEZdwnnh33GZKw0qn/NSvScDvlzO3y2Sgv\nKQIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:43:39,378 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:43:39,383 DEBUG core.py Auth message = {'response': 511, 'bin': 'fd493c46052e306adc541eb863361008b268e1000f0e99a4dbd08718a34400da948306e2672099f90e1cf7b4ff2efaf2fec9596da3c80d9c8d33336c1f0c8084'}
2020-10-08 10:43:39,417 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602128618.8729362, 'user': {'account_name': 'Lena', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnQPZZ6dth0fPGaaaWoZd\nQ0PtS8kwuh/wEgXVlKwUnFS9SfZVuryA/Om8pH5n9e7pnhNRSNWXP/tXuf0/xD1t\nIBVv+wR3bBSNVEpDpBHye4r8y71MnXUmD2lCj2+B8GmDscZhyjQ0w2jC62hkDnMc\nrJ2d73RcJrrTs9OwxCW2YSJ3c79WJVLvNm6C8lUq2BKGperucH1AYlNP1nFJYMyf\n/nNnsFC0VAIw9CyciVSnFnvkHoS/BX8dQX6pwH8/pRe0dDkNtyHpte/Xz0dp/sEL\n6ixljiJHwvaGdIfU1DYC7n9o2XvWDmArXcIhhLJjtDOOuRIgh1k9hGnKqTeuMPFe\nBQIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:43:39,417 DEBUG core.py Start auth process for {'account_name': 'Lena', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnQPZZ6dth0fPGaaaWoZd\nQ0PtS8kwuh/wEgXVlKwUnFS9SfZVuryA/Om8pH5n9e7pnhNRSNWXP/tXuf0/xD1t\nIBVv+wR3bBSNVEpDpBHye4r8y71MnXUmD2lCj2+B8GmDscZhyjQ0w2jC62hkDnMc\nrJ2d73RcJrrTs9OwxCW2YSJ3c79WJVLvNm6C8lUq2BKGperucH1AYlNP1nFJYMyf\n/nNnsFC0VAIw9CyciVSnFnvkHoS/BX8dQX6pwH8/pRe0dDkNtyHpte/Xz0dp/sEL\n6ixljiJHwvaGdIfU1DYC7n9o2XvWDmArXcIhhLJjtDOOuRIgh1k9hGnKqTeuMPFe\nBQIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:43:39,432 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:43:39,433 DEBUG core.py Auth message = {'response': 511, 'bin': '8cb81c19c6e5faf39c156ce8e834c78c045d67b3bf84e231f5b880ac01a0584e9b4eff7c3f51a9d22e4f5b643b5a2e97c894e9b9e6d3d08d96c9b67692758237'}
2020-10-08 10:43:39,450 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602128618.8819335, 'user': {'account_name': 'Dima', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4elxPrXi2TC515fun2//\nC9alciCYFrphla6kOA4iVr7DcB+1NXBPAMJulJt5O3XIgny8yrRRj+kdNJ7jrDe3\nW4RglWS0hzK0OcAdNI7rxu0cAA/WM+FP0RwcjCf5A3QTTU5Z75PLGi1YaQNFe+tc\nfTm2810qq07qP/xeSQv41aS95OFLQYiRo0Vuqa3sV7EVch05bG9ZI8abo30JotDf\nVau4qFJNgCDuwMZWHtTFeWCV+mngW84rWJHcJIm4aQpZRXIcHCxAdvByihv3HxN5\nUeNAca6DmDojd8ye8Se0wj+oRzgTx6HSXrTrq0Ex28+JwVnpSVbJ3c5beAQuTGbC\nWwIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:43:39,450 DEBUG core.py Start auth process for {'account_name': 'Dima', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4elxPrXi2TC515fun2//\nC9alciCYFrphla6kOA4iVr7DcB+1NXBPAMJulJt5O3XIgny8yrRRj+kdNJ7jrDe3\nW4RglWS0hzK0OcAdNI7rxu0cAA/WM+FP0RwcjCf5A3QTTU5Z75PLGi1YaQNFe+tc\nfTm2810qq07qP/xeSQv41aS95OFLQYiRo0Vuqa3sV7EVch05bG9ZI8abo30JotDf\nVau4qFJNgCDuwMZWHtTFeWCV+mngW84rWJHcJIm4aQpZRXIcHCxAdvByihv3HxN5\nUeNAca6DmDojd8ye8Se0wj+oRzgTx6HSXrTrq0Ex28+JwVnpSVbJ3c5beAQuTGbC\nWwIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:43:39,467 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:43:39,468 DEBUG core.py Auth message = {'response': 511, 'bin': 'fdd7760e4beaf0023f6fb3d5f24b6eadbb1d42ff5f1bac495ab482122e3c8669f1855b1d0f59b6dfe49da7de2c4842364787194b16517678d05417427c279465'}
2020-10-08 10:43:39,986 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1602128619.385469, 'account_name': 'Oleg'}
2020-10-08 10:43:40,009 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1602128619.43445, 'account_name': 'Lena'}
2020-10-08 10:43:40,024 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1602128619.4694502, 'account_name': 'Dima'}
2020-10-08 10:43:40,526 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1602128620.0438385, 'user': 'Oleg'}
2020-10-08 10:43:40,533 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1602128620.0458384, 'user': 'Lena'}
2020-10-08 10:43:40,543 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1602128620.048838, 'user': 'Dima'}
2020-10-08 10:43:53,062 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1602128632.5721369, 'account_name': 'Lena'}
2020-10-08 10:43:55,068 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1602128634.7173407, 'account_name': 'Dima'}
2020-10-08 10:44:37,172 DEBUG core.py Getting data from client exception.
Traceback (most recent call last):
  File "C:\Users\User\Projects\MessengerProject\server\core.py", line 57, in run
    receive_message(client_with_message), client_with_message)
  File "C:\Users\User\Projects\MessengerProject\general\utils.py", line 7, in receive_message
    enc_answer = client.recv(MAX_PACKAGE_LEN)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2020-10-08 10:44:37,173 INFO core.py Клиент ('127.0.0.1', 62828) отключился от сервера.
2020-10-08 10:44:38,193 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1602128678.17505, 'account_name': 'Lena'}
2020-10-08 10:44:38,193 INFO core.py Клиент ('127.0.0.1', 62829) отключился от сервера.
2020-10-08 10:44:41,212 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1602128680.9992096, 'account_name': 'Dima'}
2020-10-08 10:44:41,212 INFO core.py Клиент ('127.0.0.1', 62830) отключился от сервера.
2020-10-08 10:44:53,018 DEBUG decors.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2020-10-08 10:44:53,018 DEBUG decors.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2020-10-08 10:44:53,020 DEBUG decors.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2020-10-08 10:44:53,020 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2020-10-08 10:44:53,021 DEBUG server.py Аргументы успешно загружены.
2020-10-08 10:44:53,060 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2020-10-08 10:44:58,939 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62839)
2020-10-08 10:44:58,939 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62840)
2020-10-08 10:44:58,955 INFO core.py Установлено соедение с ПК ('127.0.0.1', 62841)
2020-10-08 10:44:59,456 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602128698.955926, 'user': {'account_name': 'Lena', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnQPZZ6dth0fPGaaaWoZd\nQ0PtS8kwuh/wEgXVlKwUnFS9SfZVuryA/Om8pH5n9e7pnhNRSNWXP/tXuf0/xD1t\nIBVv+wR3bBSNVEpDpBHye4r8y71MnXUmD2lCj2+B8GmDscZhyjQ0w2jC62hkDnMc\nrJ2d73RcJrrTs9OwxCW2YSJ3c79WJVLvNm6C8lUq2BKGperucH1AYlNP1nFJYMyf\n/nNnsFC0VAIw9CyciVSnFnvkHoS/BX8dQX6pwH8/pRe0dDkNtyHpte/Xz0dp/sEL\n6ixljiJHwvaGdIfU1DYC7n9o2XvWDmArXcIhhLJjtDOOuRIgh1k9hGnKqTeuMPFe\nBQIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:44:59,456 DEBUG core.py Start auth process for {'account_name': 'Lena', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnQPZZ6dth0fPGaaaWoZd\nQ0PtS8kwuh/wEgXVlKwUnFS9SfZVuryA/Om8pH5n9e7pnhNRSNWXP/tXuf0/xD1t\nIBVv+wR3bBSNVEpDpBHye4r8y71MnXUmD2lCj2+B8GmDscZhyjQ0w2jC62hkDnMc\nrJ2d73RcJrrTs9OwxCW2YSJ3c79WJVLvNm6C8lUq2BKGperucH1AYlNP1nFJYMyf\n/nNnsFC0VAIw9CyciVSnFnvkHoS/BX8dQX6pwH8/pRe0dDkNtyHpte/Xz0dp/sEL\n6ixljiJHwvaGdIfU1DYC7n9o2XvWDmArXcIhhLJjtDOOuRIgh1k9hGnKqTeuMPFe\nBQIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:44:59,465 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:44:59,470 DEBUG core.py Auth message = {'response': 511, 'bin': 'd9523d1c9feb9f9312c2ae549fcc40ef279655619e75ee38058bb0caa7354f247289b5b69eac87c36f6993f63116764a301fa5b84f8c41fb462b5880934da3b8'}
2020-10-08 10:44:59,513 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602128698.956927, 'user': {'account_name': 'Oleg', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzmCkZjMvTvTMorCc40Rx\nmHegO56XAPOREx34/aw04ptZPog7EL32K4FbeBYh4DrPAWeoFcB6ZiaijviFe6P9\nyrBT59G0AbJFfD+wPKra2ZLhkk1WOSolMNJT4bZwV7IcpyzVTj1V98N5AdIYZXDf\nFRtRSVQWkYJP63Soq2IaXIzaJLKPraIeINh6RGlLTEdjQmTTsK5+txwso3vn2xd3\n9rO86OjKcPZYtO9YizNuS7WnZUD0VFS6VP7yu0G3VU+iv7d0XvLZiE60Xp7adrwJ\nEl10TeQDZ6whQAkY0BmoXmfC+4BCQRPEZdwnnh33GZKw0qn/NSvScDvlzO3y2Sgv\nKQIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:44:59,513 DEBUG core.py Start auth process for {'account_name': 'Oleg', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzmCkZjMvTvTMorCc40Rx\nmHegO56XAPOREx34/aw04ptZPog7EL32K4FbeBYh4DrPAWeoFcB6ZiaijviFe6P9\nyrBT59G0AbJFfD+wPKra2ZLhkk1WOSolMNJT4bZwV7IcpyzVTj1V98N5AdIYZXDf\nFRtRSVQWkYJP63Soq2IaXIzaJLKPraIeINh6RGlLTEdjQmTTsK5+txwso3vn2xd3\n9rO86OjKcPZYtO9YizNuS7WnZUD0VFS6VP7yu0G3VU+iv7d0XvLZiE60Xp7adrwJ\nEl10TeQDZ6whQAkY0BmoXmfC+4BCQRPEZdwnnh33GZKw0qn/NSvScDvlzO3y2Sgv\nKQIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:44:59,524 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:44:59,525 DEBUG core.py Auth message = {'response': 511, 'bin': 'c32c6709d8a4e63a629c08cf6b9912fa73d52fedd8144ee1dea05c11a0924d6cde47ba1296bc26589430a08ec00807f68c41be51b6685ef0d271b5e3f0ae7b23'}
2020-10-08 10:44:59,534 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1602128698.9679317, 'user': {'account_name': 'Dima', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4elxPrXi2TC515fun2//\nC9alciCYFrphla6kOA4iVr7DcB+1NXBPAMJulJt5O3XIgny8yrRRj+kdNJ7jrDe3\nW4RglWS0hzK0OcAdNI7rxu0cAA/WM+FP0RwcjCf5A3QTTU5Z75PLGi1YaQNFe+tc\nfTm2810qq07qP/xeSQv41aS95OFLQYiRo0Vuqa3sV7EVch05bG9ZI8abo30JotDf\nVau4qFJNgCDuwMZWHtTFeWCV+mngW84rWJHcJIm4aQpZRXIcHCxAdvByihv3HxN5\nUeNAca6DmDojd8ye8Se0wj+oRzgTx6HSXrTrq0Ex28+JwVnpSVbJ3c5beAQuTGbC\nWwIDAQAB\n-----END PUBLIC KEY-----'}}
2020-10-08 10:44:59,534 DEBUG core.py Start auth process for {'account_name': 'Dima', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4elxPrXi2TC515fun2//\nC9alciCYFrphla6kOA4iVr7DcB+1NXBPAMJulJt5O3XIgny8yrRRj+kdNJ7jrDe3\nW4RglWS0hzK0OcAdNI7rxu0cAA/WM+FP0RwcjCf5A3QTTU5Z75PLGi1YaQNFe+tc\nfTm2810qq07qP/xeSQv41aS95OFLQYiRo0Vuqa3sV7EVch05bG9ZI8abo30JotDf\nVau4qFJNgCDuwMZWHtTFeWCV+mngW84rWJHcJIm4aQpZRXIcHCxAdvByihv3HxN5\nUeNAca6DmDojd8ye8Se0wj+oRzgTx6HSXrTrq0Ex28+JwVnpSVbJ3c5beAQuTGbC\nWwIDAQAB\n-----END PUBLIC KEY-----'}
2020-10-08 10:44:59,544 DEBUG core.py Correct username, starting passwd check.
2020-10-08 10:44:59,545 DEBUG core.py Auth message = {'response': 511, 'bin': '661a52679c98c6abb76e54510325648b55ff6d4a8e71f821ae782d62dc3db6c9e71ed27e8a2d2ed76ccb5bc328d32751501e0393d3981b876da2482df6d758d1'}
2020-10-08 10:45:00,053 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1602128699.4724004, 'account_name': 'Lena'}
2020-10-08 10:45:00,063 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1602128699.5264199, 'account_name': 'Oleg'}
2020-10-08 10:45:00,063 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1602128699.5463953, 'account_name': 'Dima'}
2020-10-08 10:45:00,565 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1602128700.082653, 'user': 'Lena'}
2020-10-08 10:45:00,573 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1602128700.0836532, 'user': 'Oleg'}
2020-10-08 10:45:00,579 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1602128700.0836532, 'user': 'Dima'}
2020-10-08 10:45:14,612 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1602128714.6077027, 'account_name': 'Dima'}
2020-10-08 10:45:20,122 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'Lena', 'to': 'Dima', 'time': 1602128719.6239717, 'message_text': 'GeyI/clH/RKhrLXuyprNYA2RTKs2/bbXwoknzH1n7gnn+O/vu+hvrfUL/FzU1+dj/F9m+vTncthue3D30JA/qMZQWb53Apoa39/Ua9D1SEPpM9W4osprF64TQ5GGpM/1fTqs+qe9aZnpqDNCO+zG//I0ZZpa/I3r/Dtgk4YNvMZpuuWxzJKRccYObl11r5XZ3eSSp4HTKkGhI90kvK3ULoxJ7l8qz6VGoeXtdyP1+N5h8Hn3AM5e0JCe0LIzj51UbozBlFGG021gUVsQZaTbUUOBR8VPme/EWc7D3r7zFJShbgEQnbs9Ge4OgwoyGNifOhKxTey+UUSzYGQTTy47vw=='}
2020-10-08 10:45:20,146 INFO core.py Отправлено сообщение пользователю Dima от пользователя Lena.
2020-10-08 10:45:23,648 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1602128722.8165662, 'account_name': 'Lena'}
2020-10-08 10:45:29,654 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'Dima', 'to': 'Lena', 'time': 1602128729.5669847, 'message_text': 'HuOPGTYk4JEDV/WUPBLR9+WavuG1ec2YRSc7t/AUbDSibwRHCWYBJGKAfidQR3AkGPOTp8j2p+nq9FMAnD5Drr2HOrYciUsMlTURBEbwX/bhdgOx2VrhvBcJPXqlYaxc4U1EBgCJMEKc0lzRBk9U2pPaNezLg/T9fFTnse7pvWZtvgT8XFO5HcGsr3sHwQ44Kj55kR31sHc7Me4omNCVQUQUxbqMYfx/98f7seJq16/4d6foVPX3OKXfAngnMSi+kzsrmYqVl6lLY/2sp8/BMUtIL3c17YjcLNpRsnygx0oYGlQpD8orP//tNyW5M/vCEDz9mAHbbeCfYFTm+NSxHQ=='}
2020-10-08 10:45:29,697 INFO core.py Отправлено сообщение пользователю Lena от пользователя Dima.
2020-10-08 10:45:36,205 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'Lena', 'to': 'Dima', 'time': 1602128735.9118073, 'message_text': 'PTBsXvGe1IB0DbNuRhDzBb8k2evhN9MZWDxBjpCTWuDbYon8ZhHgqcvjnM7rU1iXu87sY8FGEpmyIYg8mWJWN2sfHNp97t4sFwXCArjCSiKXtW34x5b4MT1GE3STO9Cggg4GFrsV9qKcJXQwRtPl2xIg4Acjp3ZlipUDRk+/d/AY1vNFol61Ubzc57ugzSXySEg3FpgHA63GmpIV63zUY7z1yfkKTDGF4zS4JzFa5v+kYGMnLye8SwI+gdeZxZNiZuUc94H7qshLjbmRSU9a2mxR/Ld4vg3ql1m2B+eSfS57oFX7NTYAFeCVeYqBWRXElbKfqCCy3E9+HSO2PPbDCw=='}
2020-10-08 10:45:36,251 INFO core.py Отправлено сообщение пользователю Dima от пользователя Lena.
2020-10-08 10:45:44,259 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1602128744.1828246, 'account_name': 'Dima'}
2020-10-08 10:45:44,259 INFO core.py Клиент ('127.0.0.1', 62841) отключился от сервера.
2020-10-08 10:45:45,296 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1602128745.2062504, 'account_name': 'Lena'}
2020-10-08 10:45:45,296 INFO core.py Клиент ('127.0.0.1', 62839) отключился от сервера.
2020-10-08 10:45:46,815 DEBUG core.py Getting data from client exception.
Traceback (most recent call last):
  File "C:\Users\User\Projects\MessengerProject\server\core.py", line 57, in run
    receive_message(client_with_message), client_with_message)
  File "C:\Users\User\Projects\MessengerProject\general\utils.py", line 7, in receive_message
    enc_answer = client.recv(MAX_PACKAGE_LEN)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2020-10-08 10:45:46,817 INFO core.py Клиент ('127.0.0.1', 62840) отключился от сервера.
